####  Create 2-D array

In [12]:
import numpy as np

In [14]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [15]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

####  Indexing using double bracket notation

In [17]:
matrix[0][1]

10

In [18]:
matrix[1][1]

25

#### Indexing Using single bracketr Notation

In [20]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
matrix[0,1]

10

In [23]:
matrix[2,1]

40

   #### Slicing unsing single bracket noatation

In [24]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [26]:
matrix[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [27]:
matrix[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [28]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [35]:
np.random.seed(123)
matrix2 = np.random.randint(1,101,25).reshape(5,5)

In [30]:
matrix2

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84, 79,
       37, 97, 81, 69, 50, 56, 68,  3])

In [31]:
matrix2.reshape(5,5)

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [34]:
matrix2

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84, 79,
       37, 97, 81, 69, 50, 56, 68,  3])