In [1]:
import numpy as np

In [2]:
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,3)

In [3]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [4]:
np.sum(matrix)

39

In [5]:
np.max(matrix)

10

In [6]:
np.min(matrix)

1

In [7]:
matrix.sum()

39

####  row= 1 col =0

In [8]:
np.min(matrix,axis=1)

array([3, 2, 1])

In [10]:
np.min(matrix,axis=0)

array([2, 2, 1])

In [11]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

#### Horizonal and Vertical Stacking

In [13]:
np.random.seed(123)
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(20,40,9).reshape(3,3)

In [14]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [15]:
matrix2 

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [19]:
np.hstack((matrix1, matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [20]:
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])