### Import numpy library  

In [1]:
import numpy as np

### Create an Array using array function  

In [14]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

### Create an Array containing numbers from 20 to 40 

In [18]:
array2 = np.arange(20,41)
array2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

### Create an array which contain 10 elements and every element is 5  

In [21]:
fives = np.ones(10)*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create a 1-d array and then convert it into 3-d array  

In [22]:
arr3 = np.random.randint(1,50,24).reshape(3,4,2)
arr3

array([[[22, 29],
        [45, 18],
        [34, 23],
        [32, 13]],

       [[44, 17],
        [25, 15],
        [14, 20],
        [11, 34]],

       [[12,  8],
        [39, 16],
        [14,  2],
        [15, 22]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [24]:
arr4 = np.random.rand(4,5)
arr4

array([[0.11156355, 0.00536314, 0.13919411, 0.51525538, 0.79208209],
       [0.61471917, 0.44073772, 0.71973942, 0.03421937, 0.16009757],
       [0.03213526, 0.34244306, 0.63616564, 0.96555157, 0.64619892],
       [0.17112189, 0.61426312, 0.00932557, 0.57012152, 0.52192874]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [26]:
np.random.seed(123)
arr5 = np.random.randint(1,50,20)
arr5[arr5%2 ==0]=-1
arr5

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [29]:
matrix = np.array([[5 , 10, 15, 20, 25],
                   [30, 35, 40, 45, 50],
                   [55, 60, 65, 70, 75],
                   [80, 85, 90, 95, 100]])
matrix


array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [31]:
matrix[1:3,0:3]

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [35]:
arr7 = np.array([1,2,3])
arr8 = np.array([4,5,6])
np.hstack((arr7,arr8))

array([1, 2, 3, 4, 5, 6])

### Stack 2-d matrix horizontally and vertically

In [38]:
matrix2 = np.random.randint(1,20,9).reshape(3,3)
matrix3 = np.random.randint(11,30,9).reshape(3,3)

In [39]:
matrix2

array([[16, 17,  8],
       [10,  4,  7],
       [ 2,  3,  2]])

In [40]:
matrix3

array([[23, 19, 14],
       [21, 16, 11],
       [22, 13, 21]])

In [43]:
np.hstack((matrix2,matrix3))

array([[16, 17,  8, 23, 19, 14],
       [10,  4,  7, 21, 16, 11],
       [ 2,  3,  2, 22, 13, 21]])

In [44]:
np.vstack((matrix2,matrix3))

array([[16, 17,  8],
       [10,  4,  7],
       [ 2,  3,  2],
       [23, 19, 14],
       [21, 16, 11],
       [22, 13, 21]])