In [2]:
import numpy as np

#### Zero is used for store zero value 

In [4]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

####  One in diagonal

In [5]:
arr = np.ones(2)
arr

array([1., 1.])

In [6]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### eye is used for diagonal zero 


In [7]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr = np.eye(3,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

#### dia is used for inser element on diagonal or find the diagonal element

In [10]:
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [12]:
arr = np.eye(4,4)
arr1 = np.diag(arr)
arr1

array([1., 1., 1., 1.])

In [13]:
ran_number = np.random.randint(1,10,5)
ran_number

array([9, 2, 7, 1, 8])

####  Reshap array is used for change the dimension array

In [26]:
arr = np.random.randint(1,100,20)
arr  = arr.reshape(2,2,5)

In [27]:
arr


array([[[31, 84, 44, 72, 22],
        [18, 27, 30, 10, 49]],

       [[44, 11, 34, 50, 80],
        [23, 21, 33, 59, 77]]])

#### -1 is used for autocalculated rows or column when you define anyone of them


In [32]:
arr = arr.reshape(2,-1)
arr

array([[31, 84, 44, 72, 22, 18, 27, 30, 10, 49],
       [44, 11, 34, 50, 80, 23, 21, 33, 59, 77]])

#####  seed is used for same random number genrate 

In [40]:
np.random.seed(15)
arr = np.random.randint(1,100,12)
arr

array([73, 13,  6,  1, 29, 28, 72, 76, 86, 48, 94, 18])